/**
 * El catálogo completo, transcrito de la nota de Apple "📺 TV" más las
 * listas de Netflix y lo que fue saliendo en conversación.
 *
 *   now   — en curso ahora mismo
 *   seen  — tildado en la nota
 *   tier  — sólo para pendientes; es donde el ranking sirve para decidir
 *   v     — veredicto, también sólo para pendientes
 *   wiki  — artículo de Wikipedia del que sale la portada
 */

export const CATALOG = [
  /* ─────────── En curso ─────────── */
  {id:"severance", t:"Severance", y:2022, ty:"serie", g:"Sci-fi", pf:"Apple TV+", now:true, wiki:"Severance (TV series)",
   v:"La mejor sci-fi de la década. La T2 cierra altísimo."},
  {id:"silo", t:"Silo", y:2023, ty:"serie", g:"Sci-fi", pf:"Apple TV+", now:true, wiki:"Silo (TV series)",
   v:"Distopía cerrada, lenta al principio, pero la mitología del silo engancha fuerte."},
  {id:"shrinking", t:"Shrinking", y:2023, ty:"serie", g:"Comedia", pf:"Apple TV+", now:true, wiki:"Shrinking (TV series)",
   v:"Comedia con duelo de fondo. Harrison Ford se roba cada escena en la que aparece."},
  {id:"the-morning-show", t:"The Morning Show", y:2019, ty:"serie", g:"Drama", pf:"Apple TV+", now:true, wiki:"The Morning Show (American TV series)",
   v:"Culebrón elegante y adictivo. Baja un escalón por temporada, pero se ve solo."},
  {id:"paradise", t:"Paradise", y:2025, ty:"serie", g:"Thriller", pf:"Disney+", now:true, wiki:"Paradise (American TV series)",
   v:"El giro del piloto justifica toda la temporada. Ojo que es de Hulu: acá va por Disney+."},

  /* ─────────── Series pendientes (bloque inicial de la nota) ─────────── */
  {id:"for-all-mankind", t:"For All Mankind", y:2019, ty:"serie", g:"Sci-fi", pf:"Apple TV+", now:true, wiki:"For All Mankind (TV series)",
   v:"Historia alternativa de la carrera espacial. Después de Severance, lo mejor del género en TV."},
  {id:"the-last-of-us", t:"The Last of Us", y:2023, ty:"serie", g:"Drama", pf:"Max", now:true, wiki:"The Last of Us (TV series)",
   v:"T1 completa, T2 a mitad de camino. La T2 arranca durísima y después se dispersa; vale terminarla."},
  {id:"welcome-to-wrexham", t:"Welcome to Wrexham", y:2022, ty:"serie", g:"Deporte", pf:"Disney+", now:true, wiki:"Welcome to Wrexham",
   v:"Fútbol galés comprado por dos actores. Mucho más emotiva de lo que suena."},
  {id:"rick-and-morty", t:"Rick and Morty", y:2013, ty:"serie", g:"Animación", pf:"Max", now:true, wiki:"Rick and Morty",
   v:"Sci-fi animada, brillante y agotadora en dosis grandes. Las primeras tres temporadas son las buenas."},
  {id:"common-side-effects", t:"Common Side Effects", y:2025, ty:"serie", g:"Animación", pf:"Max", now:true, wiki:"Common Side Effects",
   v:"Animación adulta sobre un hongo que cura todo. La rareza mejor recibida de 2025."},
  {id:"the-day-of-the-jackal", t:"The Day of the Jackal", y:2024, ty:"serie", g:"Thriller", pf:"Prime Video", now:true, wiki:"The Day of the Jackal (TV series)",
   v:"Redmayne como francotirador. Thriller de persecución muy entretenido, sin pretensiones."},
  {id:"cape-fear-2026", t:"Cape Fear", y:2026, ty:"serie", g:"Thriller", pf:"Apple TV+", now:true, wiki:"Cape Fear (miniseries)", search:"Cape Fear 2026 television series Bardem",
   v:"Arrancada con Lu. Bardem está enorme; la crítica dice que estiran la venganza a 10 capítulos y se desinfla en el medio."},
  {id:"the-night-manager", t:"The Night Manager", y:2016, ty:"serie", g:"Thriller", pf:"Prime Video", tier:"A", wiki:"The Night Manager (TV series)",
   v:"La T1 es espionaje de primera con Hiddleston y Laurie. La T2 de 2026 no le llega."},

  /* ─────────── Películas en cola (bloque 3 de la nota) ─────────── */
  {id:"the-revenant", t:"The Revenant", y:2015, ty:"peli", g:"Drama", pf:"Prime Video", tier:"A", wiki:"The Revenant (2015 film)",
   v:"Iñárritu y Lubezki. Brutal, helada y lenta, pero la fotografía sola la justifica."},
  {id:"gangs-of-new-york", t:"Gangs of New York", y:2002, ty:"peli", g:"Crimen", pf:"Netflix", tier:"A", wiki:"Gangs of New York",
   v:"Scorsese. Day-Lewis está monumental y sostiene una película desprolija."},
  {id:"blood-diamond", t:"Diamantes de sangre", y:2006, ty:"peli", g:"Thriller", pf:"Netflix", tier:"A", wiki:"Blood Diamond",
   v:"DiCaprio y Hounsou. Tensa, con un conflicto real de fondo bien contado."},
  {id:"indiana-jones", t:"Indiana Jones", y:1981, ty:"peli", g:"Acción", pf:"Disney+", tier:"A", wiki:"Raiders of the Lost Ark",
   v:"En busca del arca perdida y La última cruzada son las que valen. Las otras dos son opcionales."},
  {id:"speed", t:"Speed", y:1994, ty:"peli", g:"Acción", pf:"Netflix", tier:"B", wiki:"Speed (1994 film)",
   v:"Acción noventosa de manual, con una premisa que no afloja. Se disfruta sin pensar."},
  {id:"nosferatu", t:"Nosferatu", y:2024, ty:"peli", g:"Terror", pf:"Max", tier:"B", wiki:"Nosferatu (2024 film)",
   v:"Eggers, preciosa. Pero es terror de fuego lento y atmósfera: justo lo que ya sabés que no te va."},
  {id:"lilo-y-stitch", t:"Lilo & Stitch", y:2025, ty:"peli", g:"Animación", pf:"Disney+", tier:"B", wiki:"Lilo & Stitch (2025 film)",
   v:"El remake en imagen real. Cumple y poco más; la original de 2002 es mejor."},
  {id:"dos-tumbas", t:"Dos tumbas", y:2025, ty:"peli", g:"Thriller", pf:"Netflix", tier:"C", wiki:"Dos tumbas",
   v:"Miniserie española de venganza. Correcta y perfectamente olvidable."},

  /* ─────────── Sci Fi ─────────── */
  {id:"eternal-sunshine", t:"Eternal Sunshine of the Spotless Mind", y:2004, ty:"peli", g:"Drama", pf:"Alquiler", tier:"S", wiki:"Eternal Sunshine of the Spotless Mind",
   v:"Obra maestra. No es sci-fi de acción, pero es de las mejores películas que vas a ver en tu vida."},
  {id:"upgrade", t:"Upgrade", y:2018, ty:"peli", g:"Sci-fi", pf:"Alquiler", seen:true, wiki:"Upgrade (film)"},
  {id:"moon", t:"Moon", y:2009, ty:"peli", g:"Sci-fi", pf:"Alquiler", tier:"A", wiki:"Moon (film)",
   v:"Sam Rockwell solo en la Luna. Íntima, corta y con un giro que se gana."},
  {id:"looper", t:"Looper", y:2012, ty:"peli", g:"Sci-fi", pf:"Netflix", tier:"A", wiki:"Looper (film)",
   v:"Viajes en el tiempo con Willis y Gordon-Levitt. Sólida y con buenas ideas."},
  {id:"sunshine", t:"Sunshine", y:2007, ty:"peli", g:"Sci-fi", pf:"Alquiler", tier:"B", wiki:"Sunshine (2007 film)",
   v:"Danny Boyle. Dos tercios excelentes y un tercer acto que se desbarranca feo."},
  {id:"road-house", t:"Road House", y:2024, ty:"peli", g:"Acción", pf:"Prime Video", tier:"C", wiki:"Road House (2024 film)",
   v:"Gyllenhaal reparte piñas con carisma en una película floja. Para fondo."},

  /* ─────────── Documentales y TV ─────────── */
  {id:"prehistoric-planet", t:"Prehistoric Planet", y:2022, ty:"serie", g:"Naturaleza", pf:"Apple TV+", tier:"A", wiki:"Prehistoric Planet",
   v:"Attenborough y dinosaurios con la mejor CGI que existe."},
  {id:"mourinho-doc", t:"Mourinho", y:2025, ty:"serie", g:"Deporte", pf:"Prime Video", tier:"B", search:"Mourinho documentary series",
   v:"Docuserie del personaje más televisivo del fútbol. Entretenida, poco crítica."},
  {id:"documental-messi", t:"Documental Messi", y:2023, ty:"serie", g:"Deporte", pf:"Apple TV+", tier:"B", wiki:"Messi's World Cup: The Rise of a Legend",
   v:"El Mundial contado por él. Si sos de la camiseta, se disfruta."},

  /* ─────────── Bloque grande de películas sueltas ─────────── */
  {id:"nightcrawler", t:"Primicia mortal", y:2014, ty:"peli", g:"Thriller", pf:"Netflix", seen:true, wiki:"Nightcrawler (film)"},
  {id:"prisoners", t:"La sospecha", y:2013, ty:"peli", g:"Thriller", pf:"Netflix", tier:"S", wiki:"Prisoners (2013 film)",
   v:"Villeneuve antes de Dune, con Jackman y Gyllenhaal. Dos horas y media que no pesan."},
  {id:"incendies", t:"La mujer que cantaba", y:2010, ty:"peli", g:"Drama", pf:"Alquiler", tier:"S", wiki:"Incendies",
   v:"También Villeneuve. Devastadora, con un final que te deja mudo."},
  {id:"the-abyss", t:"The Abyss", y:1989, ty:"peli", g:"Sci-fi", pf:"Disney+", tier:"A", wiki:"The Abyss",
   v:"Cameron bajo el agua. La remasterización 4K la revivió y es tu combinación exacta."},
  {id:"nocturnal-animals", t:"Animales nocturnos", y:2016, ty:"peli", g:"Thriller", pf:"Netflix", tier:"A", wiki:"Nocturnal Animals",
   v:"Tom Ford. Dos historias entrelazadas, elegante e incómoda."},
  {id:"the-outfit", t:"El sastre de la mafia", y:2022, ty:"peli", g:"Crimen", pf:"Alquiler", tier:"A", wiki:"The Outfit (2022 film)",
   v:"Un cuarto, un sastre y mafiosos. Pequeña, hablada y muy bien escrita."},
  {id:"uncut-gems", t:"Uncut Gems", y:2019, ty:"peli", g:"Thriller", pf:"Netflix", tier:"A", wiki:"Uncut Gems",
   v:"Sandler en modo ansiedad pura. Agotadora en el mejor sentido posible."},
  {id:"ministry-ungentlemanly", t:"The Ministry of Ungentlemanly Warfare", y:2024, ty:"peli", g:"Bélico", pf:"Prime Video", tier:"B", wiki:"The Ministry of Ungentlemanly Warfare",
   v:"Guy Ritchie haciendo comandos en la Segunda Guerra. Liviana, divertida, descartable."},
  {id:"arthur-the-king", t:"Arthur the King", y:2024, ty:"peli", g:"Drama", pf:"Netflix", tier:"B", wiki:"Arthur the King",
   v:"Wahlberg y un perro en una carrera de aventura. Predecible y efectiva."},
  {id:"elvis", t:"Elvis", y:2022, ty:"peli", g:"Drama", pf:"Max", tier:"B", wiki:"Elvis (2022 film)",
   v:"Baz Luhrmann a mil por hora. Butler está enorme, el montaje agota."},
  {id:"elijo-creer", t:"Elijo creer", y:2022, ty:"peli", g:"Deporte", pf:"Star+", tier:"B", wiki:"Elijo creer",
   v:"El Mundial desde adentro de la Selección. Si te gustó Muchachos, es lo mismo con otro tono."},
  {id:"muchachos", t:"Muchachos, la película de la gente", y:2023, ty:"peli", g:"Deporte", pf:"Netflix", tier:"B", wiki:"Muchachos, la película de la gente",
   v:"El Mundial desde la tribuna. Emotiva y hecha para llorar, sin disimularlo."},

  /* ─────────── Argentinas: Darín y Francella ─────────── */
  {id:"el-secreto-de-sus-ojos", t:"El secreto de sus ojos", y:2009, ty:"peli", g:"Thriller", pf:"Netflix", seen:true, wiki:"The Secret in Their Eyes"},
  {id:"nueve-reinas", t:"Nueve reinas", y:2000, ty:"peli", g:"Crimen", pf:"Netflix", tier:"S", wiki:"Nine Queens",
   v:"La estafa argentina perfecta. Darín en el papel que lo definió."},
  {id:"esperando-la-carroza", t:"Esperando la carroza", y:1985, ty:"peli", g:"Comedia", pf:"Netflix", tier:"S", wiki:"Esperando la carroza",
   v:"Clásico absoluto. Se cita entera y vas a entender media conversación argentina después."},
  {id:"el-hijo-de-la-novia", t:"El hijo de la novia", y:2001, ty:"peli", g:"Drama", pf:"Netflix", tier:"A", wiki:"Son of the Bride",
   v:"Campanella y Darín. Emotiva sin ser tramposa, que es lo difícil."},
  {id:"el-clan", t:"El Clan", y:2015, ty:"peli", g:"Crimen", pf:"Netflix", tier:"A", wiki:"The Clan (2015 film)",
   v:"Francella irreconocible como Arquímedes Puccio. Perturbadora de verdad."},
  {id:"la-odisea-de-los-giles", t:"La odisea de los giles", y:2019, ty:"peli", g:"Comedia", pf:"Netflix", tier:"A", wiki:"Heroic Losers",
   v:"Darín padre e hijo en una comedia de atraco post-corralito. Muy bien armada."},
  {id:"el-amor-menos-pensado", t:"El amor menos pensado", y:2018, ty:"peli", g:"Comedia", pf:"Netflix", tier:"B", wiki:"An Unexpected Love",
   v:"Darín y Mercedes Morán separándose a los cincuenta. Amable y bien actuada."},
  {id:"corazon-de-leon", t:"Corazón de león", y:2013, ty:"peli", g:"Comedia", pf:"Netflix", tier:"B", wiki:"Corazón de León",
   v:"Comedia romántica de Francella. Liviana y correcta."},
  {id:"un-viaje-de-diez-metros", t:"Un viaje de diez metros", y:2014, ty:"peli", g:"Drama", pf:"Netflix", tier:"B", wiki:"The Hundred-Foot Journey (film)",
   v:"No es argentina, pero es amable, gastronómica y linda. Para una noche tranquila."},

  /* ─────────── Series & Películas: el bloque largo ─────────── */
  {id:"ciudad-de-dios", t:"Ciudad de Dios", y:2002, ty:"peli", g:"Crimen", pf:"Netflix", tier:"S", wiki:"City of God (2002 film)",
   v:"De las mejores películas de este siglo. Energía brutal, no la vas a olvidar."},
  {id:"the-departed", t:"The Departed", y:2006, ty:"peli", g:"Crimen", pf:"Netflix", tier:"S", wiki:"The Departed",
   v:"Scorsese con DiCaprio, Damon y Nicholson. Impecable de punta a punta."},
  {id:"gone-girl", t:"Gone Girl", y:2014, ty:"peli", g:"Thriller", pf:"Netflix", tier:"S", wiki:"Gone Girl (film)",
   v:"Fincher. El giro de la mitad es de los mejores que se hayan filmado."},
  {id:"shawshank", t:"Sueños de libertad", y:1994, ty:"peli", g:"Drama", pf:"Netflix", tier:"S", wiki:"The Shawshank Redemption",
   v:"La mejor puntuada de IMDb desde hace veinte años, y no es un accidente."},
  {id:"spotlight", t:"Spotlight", y:2015, ty:"peli", g:"Drama", pf:"Netflix", tier:"S", wiki:"Spotlight (film)",
   v:"Periodismo de investigación sin épica barata. Ganó el Oscar y se lo merecía."},
  {id:"snatch", t:"Snatch", y:2000, ty:"peli", g:"Crimen", pf:"Netflix", tier:"A", wiki:"Snatch (film)",
   v:"Guy Ritchie en su mejor momento. Divertidísima y con Pitt incomprensible a propósito."},
  {id:"black-swan", t:"Cisne negro", y:2010, ty:"peli", g:"Thriller", pf:"Netflix", tier:"A", wiki:"Black Swan (film)",
   v:"Aronofsky. Intensa, perturbadora, con Portman ganándose el Oscar."},
  {id:"cast-away", t:"Náufrago", y:2000, ty:"peli", g:"Drama", pf:"Netflix", tier:"A", wiki:"Cast Away",
   v:"Hanks solo en una isla durante una hora. Aguanta perfecto."},
  {id:"rain-man", t:"Rain Man", y:1988, ty:"peli", g:"Drama", pf:"Netflix", tier:"A", wiki:"Rain Man",
   v:"Hoffman y Cruise. Envejeció mucho mejor de lo que se esperaría."},
  {id:"kiss-kiss-bang-bang", t:"Kiss Kiss Bang Bang", y:2005, ty:"peli", g:"Crimen", pf:"Alquiler", tier:"A", wiki:"Kiss Kiss Bang Bang",
   v:"Downey Jr. y Kilmer en una comedia negra ingeniosa que casi nadie vio."},
  {id:"el-patron-del-mal", t:"Escobar: el patrón del mal", y:2012, ty:"serie", g:"Crimen", pf:"Netflix", tier:"A", wiki:"Escobar, el patrón del mal",
   v:"Muy por encima de Narcos. Son 74 capítulos, eso sí."},
  {id:"the-newsroom", t:"The Newsroom", y:2012, ty:"serie", g:"Drama", pf:"Max", tier:"A", wiki:"The Newsroom (American TV series)",
   v:"Sorkin puro: diálogos a mil y sermón cada tanto. Si bancás lo segundo, es excelente."},
  {id:"ghostbusters", t:"Ghostbusters", y:1984, ty:"peli", g:"Comedia", pf:"Netflix", tier:"A", wiki:"Ghostbusters",
   v:"Clásico ochentoso que se sostiene entero. Murray improvisando media película."},
  {id:"a-star-is-born", t:"Nace una estrella", y:2018, ty:"peli", g:"Drama", pf:"Max", tier:"A", wiki:"A Star Is Born (2018 film)",
   v:"Cooper y Gaga. Funciona bastante mejor de lo que uno espera de un remake."},
  {id:"triangle-of-sadness", t:"Triangle of Sadness", y:2022, ty:"peli", g:"Comedia", pf:"Max", tier:"B", wiki:"Triangle of Sadness",
   v:"Sátira de ricos. El segundo acto es memorable, el tercero se estira demasiado."},
  {id:"the-creator", t:"The Creator", y:2023, ty:"peli", g:"Sci-fi", pf:"Disney+", tier:"B", wiki:"The Creator (2023 film)",
   v:"Espectacular visualmente, guion flojo. Pero es sci-fi de acción, que es lo tuyo."},
  {id:"wanted", t:"Wanted", y:2008, ty:"peli", g:"Acción", pf:"Netflix", tier:"B", wiki:"Wanted (2008 film)",
   v:"Balas que doblan en el aire y cero verosimilitud. Se disfruta si la tomás así."},
  {id:"borg-mcenroe", t:"Borg vs McEnroe", y:2017, ty:"peli", g:"Deporte", pf:"Netflix", tier:"B", wiki:"Borg vs McEnroe",
   v:"La final de Wimbledon del 80. Correcta, con buen trabajo de los dos protagonistas."},
  {id:"diciembre-2001", t:"Diciembre 2001", y:2023, ty:"serie", g:"Drama", pf:"Star+", tier:"B", wiki:"Diciembre 2001",
   v:"Los días del corralito desde adentro de la Rosada. Interesante más por el tema que por la serie."},
  {id:"murder-orient-express", t:"Muerte en el Expreso de Oriente", y:2017, ty:"peli", g:"Thriller", pf:"Disney+", tier:"B", wiki:"Murder on the Orient Express (2017 film)",
   v:"Branagh y su bigote. Elegante, correcta y sin ninguna urgencia."},
  {id:"we-are-marshall", t:"Somos Marshall", y:2006, ty:"peli", g:"Deporte", pf:"Netflix", tier:"B", wiki:"We Are Marshall",
   v:"Deporte y tragedia, fórmula conocida. McConaughey la levanta un poco."},
  {id:"ghostbusters-afterlife", t:"Ghostbusters: Afterlife", y:2021, ty:"peli", g:"Comedia", pf:"Netflix", tier:"B", wiki:"Ghostbusters: Afterlife",
   v:"Nostalgia bien administrada. Menor que la original, pero simpática."},
  {id:"brother-bear", t:"Tierra de osos", y:2003, ty:"peli", g:"Animación", pf:"Disney+", tier:"B", wiki:"Brother Bear",
   v:"Disney de la época floja, pero tiene corazón y dura 85 minutos."},
  {id:"the-orphan", t:"La huérfana", y:2009, ty:"peli", g:"Terror", pf:"Netflix", tier:"B", wiki:"Orphan (film)",
   v:"Terror con un giro que se recuerda. Efectiva dentro de lo suyo."},
  {id:"frankie-and-johnny", t:"Frankie y Johnny", y:1991, ty:"peli", g:"Drama", pf:"Alquiler", tier:"B", wiki:"Frankie and Johnny (1991 film)",
   v:"Pacino y Pfeiffer en modo bajo. Romántica de las tranquilas."},
  {id:"house-of-gucci", t:"House of Gucci", y:2021, ty:"peli", g:"Drama", pf:"Prime Video", tier:"C", wiki:"House of Gucci",
   v:"Elenco enorme, película desprolija y acentos para el olvido. Larguísima."},
  {id:"the-call-of-the-wild", t:"El llamado salvaje", y:2020, ty:"peli", g:"Drama", pf:"Disney+", tier:"C", wiki:"The Call of the Wild (2020 film)",
   v:"El perro es CGI y se nota en cada plano. Rompe la película entera."},
  {id:"shall-we-dance", t:"Bailemos", y:2004, ty:"peli", g:"Comedia", pf:"Netflix", tier:"C", wiki:"Shall We Dance (2004 film)",
   v:"Remake blando de una japonesa muy superior. Prescindible."},
  {id:"what-men-want", t:"What Men Want", y:2019, ty:"peli", g:"Comedia", pf:"Netflix", tier:"C", wiki:"What Men Want",
   v:"Comedia de premisa gastada. Taraji P. Henson merecía mejor material."},
  {id:"3096-dias", t:"3096 días", y:2013, ty:"peli", g:"Drama", pf:"Netflix", tier:"C", wiki:"3096 Days",
   v:"El caso Kampusch. Durísima y no particularmente bien hecha."},
  {id:"paranoia", t:"Paranoia", y:2013, ty:"peli", g:"Thriller", pf:"Netflix", tier:"C", wiki:"Paranoia (2013 film)",
   v:"Thriller corporativo con Ford y Oldman desperdiciados. Genérica."},
  {id:"papa-se-volvio-loco", t:"Papá se volvió loco", y:2005, ty:"peli", g:"Comedia", pf:"Netflix", tier:"C", search:"Papá se volvió loco 2005 film",
   v:"Comedia familiar de relleno. Sólo si no queda nada más."},

  {id:"shooter-2007", t:"Shooter: el tirador", y:2007, ty:"peli", g:"Acción", pf:"Netflix", tier:"B", wiki:"Shooter (2007 film)",
   v:"Fuqua y Wahlberg. El oficio del francotirador está tomado en serio; la conspiración de fondo es pulpa pura. La serie de 2016 no vale la pena."},
  {id:"war-machine-2026", t:"War Machine", y:2026, ty:"peli", g:"Acción", pf:"Netflix", tier:"B", wiki:"War Machine (2026 film)",
   v:"Sci-fi de acción con Alan Ritchson, el de Reacher. 106 minutos, sin pretensiones. Ojo: no confundir con la de Brad Pitt de 2017."},
  {id:"mickey-17", t:"Mickey 17", y:2025, ty:"peli", g:"Sci-fi", pf:"Max", tier:"B", wiki:"Mickey 17",
   v:"Bong Joon-ho después de Parásitos, con Pattinson por duplicado. La primera mitad es buenísima; la segunda se convierte en caricatura política y se desinfla."},
  {id:"the-social-network", t:"La red social", y:2010, ty:"peli", g:"Drama", pf:"Netflix", seen:true, wiki:"The Social Network"},
  {id:"moneyball", t:"Moneyball", y:2011, ty:"peli", g:"Deporte", pf:"Netflix", seen:true, wiki:"Moneyball (film)"},
  {id:"ford-v-ferrari", t:"Contra lo imposible", y:2019, ty:"peli", g:"Deporte", pf:"Disney+", seen:true, wiki:"Ford v Ferrari"},
  {id:"senna", t:"Senna", y:2010, ty:"peli", g:"Deporte", pf:"Prime Video", seen:true, wiki:"Senna (film)"},
  {id:"rush", t:"Rush", y:2013, ty:"peli", g:"Deporte", pf:"Netflix", seen:true, wiki:"Rush (2013 film)"},
  {id:"the-big-short", t:"La gran apuesta", y:2015, ty:"peli", g:"Drama", pf:"Netflix", seen:true, wiki:"The Big Short (film)"},
  {id:"icarus", t:"Ícaro", y:2017, ty:"peli", g:"Documental", pf:"Netflix", tier:"A", wiki:"Icarus (2017 film)",
   v:"Empieza como un experimento casero con dopaje y termina destapando el fraude de Estado ruso. Ganó el Oscar."},
  {id:"beckham", t:"Beckham", y:2023, ty:"serie", g:"Deporte", pf:"Netflix", tier:"A", wiki:"Beckham (miniseries)",
   v:"Cuatro capítulos, del penal del 98 al Madrid. Mucho más honesta de lo que se esperaría de un documental autorizado."},
  {id:"sunderland-til-i-die", t:"Sunderland hasta la muerte", y:2018, ty:"serie", g:"Deporte", pf:"Netflix", tier:"A", wiki:"Sunderland 'Til I Die",
   v:"El reverso de Wrexham: un club que se hunde y una ciudad que lo sufre. Durísima y honesta."},
  {id:"dumb-money", t:"Dumb Money", y:2023, ty:"peli", g:"Drama", pf:"Netflix", tier:"B", wiki:"Dumb Money",
   v:"El caso GameStop contra los fondos de Wall Street. Liviana y entretenida, sin la profundidad de La gran apuesta."},
  {id:"ex-machina", t:"Ex Machina", y:2014, ty:"peli", g:"Sci-fi", pf:"Prime Video", seen:true, wiki:"Ex Machina (film)"},
  {id:"limitless-hemsworth", t:"Limitless con Chris Hemsworth", y:2022, ty:"serie", g:"Documental", pf:"Disney+", tier:"B", wiki:"Limitless with Chris Hemsworth",
   v:"Hemsworth sometiéndose a desafíos brutales para envejecer mejor. La ciencia es liviana, la producción es enorme, y el capítulo del gen del Alzheimer es genuino."},
  {id:"foundation", t:"Foundation", y:2021, ty:"serie", g:"Sci-fi", pf:"Apple TV+", tier:"A", wiki:"Foundation (TV series)",
   v:"Asimov en space opera. La T1 es fuego lento y te va a costar, pero T2 y T3 pasan el 90% en RT y Lee Pace como el Imperio clonado vale solo. T4 confirmada para 2027."},
  {id:"slow-horses", t:"Slow Horses", y:2022, ty:"serie", g:"Thriller", pf:"Apple TV+", tier:"S", wiki:"Slow Horses",
   v:"Gary Oldman al frente del depósito de descartes del MI5. Espionaje sucio, gracioso y humano. Cinco temporadas de seis capítulos, la sexta llega en septiembre y ya hay séptima confirmada."},
  {id:"obsession-2023", t:"Obsession", y:2023, ty:"serie", g:"Thriller", pf:"Netflix", tier:"D", wiki:"Obsession (2023 TV series)",
   v:"Cuatro capítulos y se ve en una noche, pero 40% de crítica y 14% de público. La agrego porque me la pediste, no porque la recomiende."},
  {id:"harold-kumar-guantanamo", t:"Harold & Kumar Escape from Guantanamo Bay", y:2008, ty:"peli", g:"Comedia", pf:"Prime Video", tier:"C", wiki:"Harold & Kumar Escape from Guantanamo Bay",
   v:"Comedia de porro de manual, con la escena del unicornio de Neil Patrick Harris como su gran momento. Vale por esa secuencia más que por la película."},
  {id:"the-dog-stars", t:"The Dog Stars", y:2026, ty:"peli", g:"Sci-fi", pf:"Cine", tier:"B", wiki:"The Dog Stars",
   v:"Ridley Scott post-apocalíptico con Jacob Elordi. Lo mejor de él desde The Martian, pero deliberadamente apagada: mucho clima y pocos personajes a los que agarrarse."},
  {id:"the-boys", t:"The Boys", y:2019, ty:"serie", g:"Acción", pf:"Prime Video", now:true, wiki:"The Boys (TV series)",
   v:"Superhéroes como celebridades corporativas y podridas. Violenta, satírica y con Antony Starr haciendo de uno de los mejores villanos de la TV."},
  {id:"the-drama", t:"The Drama", y:2026, ty:"peli", g:"Drama", pf:"Cine", seen:true, wiki:"The Drama (film)"},
  {id:"the-mentalist", t:"The Mentalist", y:2008, ty:"serie", g:"Crimen", pf:"Prime Video", tier:"B", wiki:"The Mentalist",
   v:"No la bingees: son 151 capítulos de procedural y de corrido se nota la fórmula. De a uno por noche, Simon Baker la sostiene entera."},

  /* ─────────── Del grupo de pestañas de Safari ─────────── */
  {id:"drive-2011", t:"Drive", y:2011, ty:"peli", g:"Thriller", pf:"Prime Video", tier:"S", wiki:"Drive (2011 film)",
   v:"Gosling, sintetizadores y violencia seca. De lo más estilizado que vas a ver."},
  {id:"kill-bill", t:"Kill Bill", y:2003, ty:"peli", g:"Acción", pf:"Netflix", tier:"S", wiki:"Kill Bill: Volume 1",
   v:"Tarantino desatado. Puro placer de acción coreografiada."},
  {id:"the-nice-guys", t:"The Nice Guys", y:2016, ty:"peli", g:"Crimen", pf:"Netflix", tier:"S", wiki:"The Nice Guys",
   v:"Gosling y Crowe en la comedia negra más subestimada de la década."},
  {id:"10-cloverfield-lane", t:"10 Cloverfield Lane", y:2016, ty:"peli", g:"Thriller", pf:"Paramount+", tier:"S", wiki:"10 Cloverfield Lane",
   v:"Tres personas en un búnker y una tensión que no afloja. Justo tu combinación."},
  {id:"predestination", t:"Predestination", y:2014, ty:"peli", g:"Sci-fi", pf:"Prime Video", tier:"S", wiki:"Predestination (film)",
   v:"El mejor viaje en el tiempo filmado. Cuanto menos sepas antes, mejor."},
  {id:"get-out", t:"Get Out", y:2017, ty:"peli", g:"Terror", pf:"Netflix", tier:"S", wiki:"Get Out",
   v:"Terror con cerebro y sin fuego lento: arranca incómoda y acelera. Ganó el Oscar a guion."},
  {id:"mare-of-easttown", t:"Mare of Easttown", y:2021, ty:"serie", g:"Crimen", pf:"Max", tier:"S", wiki:"Mare of Easttown",
   v:"Siete capítulos perfectos. Kate Winslet en el mejor papel de su carrera televisiva."},
  {id:"there-will-be-blood", t:"There Will Be Blood", y:2007, ty:"peli", g:"Drama", pf:"Prime Video", tier:"A", wiki:"There Will Be Blood",
   v:"Day-Lewis monumental. Es lenta y larga, pero de las grandes del siglo."},
  {id:"nope", t:"Nope", y:2022, ty:"peli", g:"Terror", pf:"Prime Video", tier:"A", wiki:"Nope (film)",
   v:"Peele haciendo ciencia ficción de espectáculo. Más acción que sustos."},
  {id:"the-invisible-man-2020", t:"El hombre invisible", y:2020, ty:"peli", g:"Terror", pf:"Netflix", tier:"A", wiki:"The Invisible Man (2020 film)",
   v:"Thriller de acoso con una premisa vieja resuelta con inteligencia. Tensísima."},
  {id:"the-killer-2023", t:"The Killer", y:2023, ty:"peli", g:"Thriller", pf:"Netflix", tier:"A", wiki:"The Killer (2023 film)",
   v:"Fincher en modo procedimental frío. Fassbender narrando su propia rutina de sicario."},
  {id:"hit-man", t:"Hit Man", y:2023, ty:"peli", g:"Comedia", pf:"Netflix", tier:"A", wiki:"Hit Man (film)",
   v:"Linklater y Glen Powell. Divertidísima y mucho más lista de lo que aparenta."},
  {id:"juror-2", t:"Jurado n.º 2", y:2024, ty:"peli", g:"Thriller", pf:"Max", tier:"A", wiki:"Juror No. 2",
   v:"Eastwood a los 94 filmando un dilema moral impecable. Su mejor película en años."},
  {id:"black-bag", t:"Black Bag", y:2025, ty:"peli", g:"Thriller", pf:"Prime Video", tier:"A", wiki:"Black Bag (film)",
   v:"Soderbergh haciendo espionaje matrimonial. Corta, elegante y afiladísima."},
  {id:"american-hustle", t:"American Hustle", y:2013, ty:"peli", g:"Crimen", pf:"Netflix", tier:"A", wiki:"American Hustle",
   v:"Elenco enorme en modo estafa setentosa. Se disfruta de principio a fin."},
  {id:"steve-jobs", t:"Steve Jobs", y:2015, ty:"peli", g:"Drama", pf:"Prime Video", tier:"A", wiki:"Steve Jobs (film)",
   v:"Sorkin y Boyle: tres actos, tres backstage, puro diálogo. Mucho mejor que la de Kutcher."},
  {id:"blackberry", t:"BlackBerry", y:2023, ty:"peli", g:"Drama", pf:"Prime Video", tier:"A", wiki:"BlackBerry (film)",
   v:"Auge y caída contada como comedia nerviosa. Sorprendentemente buena."},
  {id:"the-founder", t:"The Founder", y:2016, ty:"peli", g:"Drama", pf:"Netflix", tier:"A", wiki:"The Founder",
   v:"Cómo McDonald's dejó de ser de los McDonald. Keaton en modo depredador."},
  {id:"atonement", t:"Expiación", y:2007, ty:"peli", g:"Drama", pf:"Netflix", tier:"A", wiki:"Atonement (2007 film)",
   v:"El plano secuencia de Dunkerque es antológico. El final te deja golpeado."},
  {id:"okja", t:"Okja", y:2017, ty:"peli", g:"Sci-fi", pf:"Netflix", tier:"A", wiki:"Okja",
   v:"Bong Joon-ho antes de Parásitos. Rara, tierna y furiosa a la vez."},
  {id:"fantastic-mr-fox", t:"El fantástico Sr. Zorro", y:2009, ty:"peli", g:"Animación", pf:"Disney+", tier:"A", wiki:"Fantastic Mr. Fox",
   v:"Wes Anderson en stop motion. Ingeniosa y preciosa, dura 87 minutos."},
  {id:"little-miss-sunshine", t:"Pequeña Miss Sunshine", y:2006, ty:"peli", g:"Comedia", pf:"Disney+", tier:"A", wiki:"Little Miss Sunshine",
   v:"Comedia de road trip familiar que envejeció perfecto. El final es memorable."},
  {id:"pursuit-of-happyness", t:"En busca de la felicidad", y:2006, ty:"peli", g:"Drama", pf:"Netflix", tier:"A", wiki:"The Pursuit of Happyness",
   v:"Will Smith y su hijo. Emotiva sin trampas, basada en una historia real."},
  {id:"challengers", t:"Challengers", y:2024, ty:"peli", g:"Drama", pf:"Prime Video", tier:"A", wiki:"Challengers (film)",
   v:"Triángulo amoroso con tenis de fondo y una banda sonora que la empuja entera."},
  {id:"alien-earth", t:"Alien: Earth", y:2025, ty:"serie", g:"Sci-fi", pf:"Disney+", tier:"A", wiki:"Alien: Earth",
   v:"Noah Hawley expandiendo la saga en serie. Siendo tuya la veta Alien, cae sola."},
  {id:"bad-sisters", t:"Bad Sisters", y:2022, ty:"serie", g:"Comedia", pf:"Apple TV+", tier:"A", wiki:"Bad Sisters",
   v:"Comedia negra irlandesa sobre cinco hermanas y un cuñado insoportable. Adictiva."},
  {id:"black-bird", t:"Black Bird", y:2022, ty:"serie", g:"True Crime", pf:"Apple TV+", tier:"A", wiki:"Black Bird (miniseries)",
   v:"Seis capítulos, Taron Egerton infiltrado en una cárcel. Paul Walter Hauser da miedo de verdad."},
  {id:"over-the-garden-wall", t:"Over the Garden Wall", y:2014, ty:"serie", g:"Animación", pf:"Max", tier:"A", wiki:"Over the Garden Wall (miniseries)",
   v:"Diez capítulos de once minutos. Una rareza otoñal preciosa que se ve en dos horas."},
  {id:"hamnet", t:"Hamnet", y:2025, ty:"peli", g:"Drama", pf:"Cine", tier:"A", wiki:"Hamnet (film)",
   v:"Chloé Zhao con Jessie Buckley y Paul Mescal. De lo más elogiado del año."},
  {id:"i-swear", t:"I Swear", y:2025, ty:"peli", g:"Drama", pf:"Cine", tier:"A", wiki:"I Swear (film)",
   v:"Biopic de un activista con Tourette. Se llevó tres BAFTA, incluido mejor actor."},
  {id:"deepwater-horizon", t:"Deepwater Horizon", y:2016, ty:"peli", g:"Acción", pf:"Netflix", tier:"B", wiki:"Deepwater Horizon (film)",
   v:"Catástrofe petrolera bien filmada. Eficaz y olvidable, pero el desastre impacta."},
  {id:"only-the-brave", t:"Only the Brave", y:2017, ty:"peli", g:"Drama", pf:"Netflix", tier:"B", wiki:"Only the Brave (2017 film)",
   v:"Bomberos forestales, historia real, final durísimo. Correcta y sentida."},
  {id:"escape-from-pretoria", t:"Escape from Pretoria", y:2020, ty:"peli", g:"Thriller", pf:"Prime Video", tier:"B", wiki:"Escape from Pretoria",
   v:"Fuga carcelaria con Radcliffe. Tensa y sencilla, sin nada que sobre."},
  {id:"imperium", t:"Imperium", y:2016, ty:"peli", g:"Thriller", pf:"Prime Video", tier:"B", wiki:"Imperium (2016 film)",
   v:"Radcliffe infiltrado entre supremacistas. Incómoda y mejor de lo que suena."},
  {id:"the-report", t:"El informe", y:2019, ty:"peli", g:"Drama", pf:"Prime Video", tier:"B", wiki:"The Report (2019 film)",
   v:"Investigación sobre la tortura de la CIA. Densa, con Adam Driver sosteniéndola."},
  {id:"the-end-of-the-tour", t:"The End of the Tour", y:2015, ty:"peli", g:"Drama", pf:"Prime Video", tier:"B", wiki:"The End of the Tour",
   v:"Cinco días de entrevista con David Foster Wallace. Es dos tipos hablando, y funciona."},
  {id:"krisha", t:"Krisha", y:2015, ty:"peli", g:"Drama", pf:"Prime Video", tier:"B", wiki:"Krisha",
   v:"Cena familiar de Acción de Gracias que se desmorona. Asfixiante y de bajo presupuesto."},
  {id:"blow-the-man-down", t:"Blow the Man Down", y:2019, ty:"peli", g:"Crimen", pf:"Prime Video", tier:"B", wiki:"Blow the Man Down",
   v:"Noir de pueblo pesquero con dos hermanas y un cadáver. Pequeña y con carácter."},
  {id:"red-eye", t:"Vuelo nocturno", y:2005, ty:"peli", g:"Thriller", pf:"Netflix", tier:"B", wiki:"Red Eye (2005 American film)",
   v:"Wes Craven en un avión con Cillian Murphy. Ochenta minutos de tensión y nada más."},
  {id:"devils-advocate", t:"El abogado del diablo", y:1997, ty:"peli", g:"Thriller", pf:"Netflix", tier:"B", wiki:"The Devil's Advocate (1997 film)",
   v:"Pacino desatado y Keanu de abogado. Excesiva de una manera muy disfrutable."},
  {id:"office-space", t:"Enredos de oficina", y:1999, ty:"peli", g:"Comedia", pf:"Disney+", tier:"B", wiki:"Office Space",
   v:"Comedia de cubículo que se volvió de culto. Corta y con frases que sobreviven."},
  {id:"caddo-lake", t:"Caddo Lake", y:2024, ty:"peli", g:"Thriller", pf:"Max", tier:"B", wiki:"Caddo Lake",
   v:"Misterio con pantano y saltos temporales. Se arma bien sobre el final."},
  {id:"kpop-demon-hunters", t:"KPop Demon Hunters", y:2025, ty:"peli", g:"Animación", pf:"Netflix", tier:"B", wiki:"KPop Demon Hunters",
   v:"El fenómeno de 2025. Animación vertiginosa y canciones que no te vas a poder sacar."},
  {id:"phoenician-scheme", t:"The Phoenician Scheme", y:2025, ty:"peli", g:"Comedia", pf:"Prime Video", tier:"B", wiki:"The Phoenician Scheme",
   v:"Wes Anderson otra vez. Si te gusta su fórmula la vas a disfrutar; si no, no."},
  {id:"crime-101", t:"Crime 101", y:2026, ty:"peli", g:"Crimen", pf:"Cine", tier:"B", wiki:"Crime 101 (2026 film)",
   v:"Hemsworth y Ruffalo en un thriller lujoso que no termina de cerrar. Comparaciones con Heat exageradas."},
  {id:"tuner", t:"Tuner", y:2025, ty:"peli", g:"Crimen", pf:"Prime Video", tier:"B", wiki:"Tuner (film)",
   v:"Afinador de pianos que descubre que sabe abrir cajas fuertes. Con Dustin Hoffman."},
  {id:"sheep-detectives", t:"The Sheep Detectives", y:2026, ty:"peli", g:"Animación", pf:"Prime Video", tier:"B", wiki:"The Sheep Detectives",
   v:"Un rebaño de ovejas resuelve el asesinato de su pastor. Elenco absurdo de grande."},
  {id:"michael-2026", t:"Michael", y:2026, ty:"peli", g:"Drama", pf:"Cine", tier:"B", wiki:"Michael (2026 film)",
   v:"El biopic de Michael Jackson, con su sobrino en el papel. Veremos qué tan complaciente sale."},
  {id:"glhfdd", t:"Good Luck, Have Fun, Don't Die", y:2025, ty:"peli", g:"Sci-fi", pf:"Cine", tier:"B", wiki:"Good Luck, Have Fun, Don't Die",
   v:"Verbinski con Sam Rockwell y viajes en el tiempo. Rarísima, para nada convencional."},
  {id:"remarkably-bright-creatures", t:"Remarkably Bright Creatures", y:2026, ty:"peli", g:"Drama", pf:"Cine", tier:"B", wiki:"Remarkably Bright Creatures",
   v:"Una viuda y un pulpo gigante resuelven un misterio familiar. Suena raro y funciona."},
  {id:"secrets-we-keep", t:"Secrets We Keep", y:2025, ty:"serie", g:"Thriller", pf:"Netflix", tier:"B", wiki:"Secrets We Keep (TV series)",
   v:"Miniserie danesa de seis capítulos sobre una niñera desaparecida. Fría y bien hecha."},
  {id:"the-undoing", t:"The Undoing", y:2020, ty:"serie", g:"Thriller", pf:"Max", tier:"B", wiki:"The Undoing (TV series)",
   v:"Kidman y Hugh Grant en un thriller de clase alta. Seis capítulos, final discutido."},
  {id:"the-sinner", t:"The Sinner", y:2017, ty:"serie", g:"Crimen", pf:"Netflix", tier:"B", wiki:"The Sinner (TV series)",
   v:"Antología: cada temporada es un caso cerrado. La primera, con Jessica Biel, es la mejor."},
  {id:"11-22-63", t:"11.22.63", y:2016, ty:"serie", g:"Sci-fi", pf:"Disney+", tier:"B", wiki:"11.22.63",
   v:"King y viajes en el tiempo para evitar lo de Kennedy. Ocho capítulos, arranca mejor de lo que termina."},
  {id:"now-you-see-me-3", t:"Now You See Me: Now You Don't", y:2025, ty:"peli", g:"Thriller", pf:"Cine", tier:"C", wiki:"Now You See Me: Now You Don't",
   v:"Tercera de magos y atracos. Más de lo mismo, con menos gracia que la primera."},
  {id:"spectre", t:"Spectre", y:2015, ty:"peli", g:"Acción", pf:"Prime Video", tier:"C", wiki:"Spectre (2015 film)",
   v:"El Bond flojo entre Skyfall y No Time to Die. Arranque espectacular y después se desinfla."},
  {id:"red-lights", t:"Luces rojas", y:2012, ty:"peli", g:"Thriller", pf:"Prime Video", tier:"C", wiki:"Red Lights (2012 film)",
   v:"Cazadores de fraudes paranormales con De Niro. Buena premisa, resolución tramposa."},
  {id:"goat", t:"GOAT", y:2026, ty:"peli", g:"Animación", pf:"Cine", tier:"B", wiki:"Goat (2026 film)",
   v:"Una cabra que quiere ser la mejor de la liga de básquet. Producida por Stephen Curry; recaudó 165 millones."},
  {id:"the-invite", t:"The Invite", y:2026, ty:"peli", g:"Comedia", pf:"Cine", tier:"A", wiki:"The Invite",
   v:"Olivia Wilde dirige a Seth Rogen, Penélope Cruz y Edward Norton en una cena que se descontrola. Buenas críticas en Sundance."},
  {id:"swapped", t:"Swapped", y:2026, ty:"peli", g:"Animación", pf:"Netflix", tier:"C", wiki:"Swapped (film)", search:"Swapped 2026 Netflix animated film",
   v:"Un bicho del bosque y un pájaro intercambian cuerpos. La crítica la destrozó; el público la banca bastante más."},

  /* ─────────── Ya vistas: de la nota, tildadas ─────────── */
  {id:"warfare", t:"Warfare", y:2025, ty:"peli", g:"Bélico", pf:"Prime Video", seen:true, wiki:"Warfare (film)"},
  {id:"benjamin-button", t:"El curioso caso de Benjamin Button", y:2008, ty:"peli", g:"Drama", pf:"Netflix", seen:true, wiki:"The Curious Case of Benjamin Button (film)"},
  {id:"the-accountant-2", t:"The Accountant 2", y:2025, ty:"peli", g:"Acción", pf:"Prime Video", seen:true, wiki:"The Accountant 2"},
  {id:"1917", t:"1917", y:2019, ty:"peli", g:"Bélico", pf:"Netflix", seen:true, wiki:"1917 (2019 film)"},
  {id:"snowpiercer", t:"Snowpiercer", y:2013, ty:"peli", g:"Sci-fi", pf:"Netflix", seen:true, wiki:"Snowpiercer"},
  {id:"community", t:"Community", y:2009, ty:"serie", g:"Comedia", pf:"Netflix", seen:true, wiki:"Community (TV series)"},
  {id:"maniac", t:"Maniac", y:2018, ty:"serie", g:"Sci-fi", pf:"Netflix", seen:true, wiki:"Maniac (miniseries)"},
  {id:"captains-of-the-world", t:"Captains of the World", y:2022, ty:"serie", g:"Deporte", pf:"Netflix", seen:true, search:"Captains of the World Netflix"},
  {id:"the-last-dance", t:"Michael Jordan: The Last Dance", y:2020, ty:"serie", g:"Deporte", pf:"Netflix", seen:true, wiki:"The Last Dance (miniseries)"},
  {id:"planet-of-the-apes", t:"Planet of the Apes", y:2011, ty:"peli", g:"Sci-fi", pf:"Disney+", seen:true, wiki:"Rise of the Planet of the Apes"},
  {id:"dune-2", t:"Dune: Parte Dos", y:2024, ty:"peli", g:"Sci-fi", pf:"Max", seen:true, wiki:"Dune: Part Two"},
  {id:"the-iron-claw", t:"The Iron Claw", y:2023, ty:"peli", g:"Drama", pf:"Max", seen:true, wiki:"The Iron Claw (film)"},
  {id:"gran-turismo", t:"Gran Turismo", y:2023, ty:"peli", g:"Deporte", pf:"Netflix", seen:true, wiki:"Gran Turismo (film)"},
  {id:"relatos-salvajes", t:"Relatos salvajes", y:2014, ty:"peli", g:"Comedia", pf:"Netflix", seen:true, wiki:"Wild Tales (film)"},
  {id:"blood-and-bone", t:"Blood and Bone", y:2009, ty:"peli", g:"Acción", pf:"Netflix", seen:true, wiki:"Blood and Bone"},
  {id:"american-gangster", t:"American Gangster", y:2007, ty:"peli", g:"Crimen", pf:"Netflix", seen:true, wiki:"American Gangster (film)"},
  {id:"the-aviator", t:"El aviador", y:2004, ty:"peli", g:"Drama", pf:"Netflix", seen:true, wiki:"The Aviator (2004 film)"},
  {id:"a-man-called-otto", t:"A Man Called Otto", y:2022, ty:"peli", g:"Drama", pf:"Netflix", seen:true, wiki:"A Man Called Otto"},
  {id:"the-punisher", t:"The Punisher", y:2017, ty:"serie", g:"Acción", pf:"Netflix", seen:true, wiki:"The Punisher (TV series)"},
  {id:"wonka", t:"Wonka", y:2023, ty:"peli", g:"Fantasía", pf:"Max", seen:true, wiki:"Wonka (film)"},
  {id:"warrior", t:"Warrior", y:2011, ty:"peli", g:"Drama", pf:"Netflix", seen:true, wiki:"Warrior (2011 film)"},
  {id:"book-of-eli", t:"El libro de los secretos", y:2010, ty:"peli", g:"Acción", pf:"Netflix", seen:true, wiki:"The Book of Eli"},
  {id:"air", t:"Air", y:2023, ty:"peli", g:"Drama", pf:"Prime Video", seen:true, wiki:"Air (2023 film)"},
  {id:"mission-impossible", t:"Misión imposible", y:1996, ty:"peli", g:"Acción", pf:"Paramount+", seen:true, wiki:"Mission: Impossible (film series)"},
  {id:"coherence", t:"Coherence", y:2013, ty:"peli", g:"Sci-fi", pf:"Alquiler", seen:true, wiki:"Coherence (film)"},
  {id:"oppenheimer", t:"Oppenheimer", y:2023, ty:"peli", g:"Drama", pf:"Prime Video", seen:true, wiki:"Oppenheimer (film)"},
  {id:"schindlers-list", t:"La lista de Schindler", y:1993, ty:"peli", g:"Drama", pf:"Netflix", seen:true, wiki:"Schindler's List"},
  {id:"across-the-spiderverse", t:"Spider-Man: Across the Spider-Verse", y:2023, ty:"peli", g:"Animación", pf:"Netflix", seen:true, wiki:"Spider-Man: Across the Spider-Verse"},
  {id:"into-the-spiderverse", t:"Spider-Man: Into the Spider-Verse", y:2018, ty:"peli", g:"Animación", pf:"Netflix", seen:true, wiki:"Spider-Man: Into the Spider-Verse"},
  {id:"eat-pray-love", t:"Comer, rezar, amar", y:2010, ty:"peli", g:"Drama", pf:"Netflix", seen:true, wiki:"Eat Pray Love"},
  {id:"tenet", t:"Tenet", y:2020, ty:"peli", g:"Sci-fi", pf:"Max", seen:true, wiki:"Tenet (film)"},
  {id:"the-pianist", t:"El pianista", y:2002, ty:"peli", g:"Drama", pf:"Netflix", seen:true, wiki:"The Pianist (2002 film)"},
  {id:"gotg-3", t:"Guardianes de la Galaxia Vol. 3", y:2023, ty:"peli", g:"Sci-fi", pf:"Disney+", seen:true, wiki:"Guardians of the Galaxy Vol. 3"},
  {id:"john-wick-4", t:"John Wick 4", y:2023, ty:"peli", g:"Acción", pf:"Prime Video", seen:true, wiki:"John Wick: Chapter 4"},
  {id:"john-wick", t:"John Wick", y:2014, ty:"peli", g:"Acción", pf:"Netflix", seen:true, wiki:"John Wick"},
  {id:"memento", t:"Memento", y:2000, ty:"peli", g:"Thriller", pf:"Netflix", seen:true, wiki:"Memento (film)"},
  {id:"her", t:"Her", y:2013, ty:"peli", g:"Drama", pf:"Netflix", seen:true, wiki:"Her (film)"},
  {id:"goodbye-lenin", t:"Good Bye, Lenin!", y:2003, ty:"peli", g:"Comedia", pf:"Max", seen:true, wiki:"Good Bye, Lenin!"},
  {id:"the-batman", t:"The Batman", y:2022, ty:"peli", g:"Acción", pf:"Max", seen:true, wiki:"The Batman (film)"},
  {id:"the-simpsons-movie", t:"Los Simpson: la película", y:2007, ty:"peli", g:"Animación", pf:"Disney+", seen:true, wiki:"The Simpsons Movie"},
  {id:"children-of-men", t:"Hijos de los hombres", y:2006, ty:"peli", g:"Sci-fi", pf:"Prime Video", seen:true, wiki:"Children of Men"},
  {id:"avatar-tlab-serie", t:"Avatar: The Last Airbender", y:2005, ty:"serie", g:"Animación", pf:"Netflix", seen:true, wiki:"Avatar: The Last Airbender"},
  {id:"ant-man-quantumania", t:"Ant-Man y la Avispa: Quantumanía", y:2023, ty:"peli", g:"Sci-fi", pf:"Disney+", seen:true, wiki:"Ant-Man and the Wasp: Quantumania"},
  {id:"justice-league-doom", t:"Justice League: Doom", y:2012, ty:"peli", g:"Animación", pf:"Max", seen:true, wiki:"Justice League: Doom"},
  {id:"drive-to-survive", t:"Fórmula 1: Drive to Survive", y:2019, ty:"serie", g:"Deporte", pf:"Netflix", seen:true, wiki:"Formula 1: Drive to Survive"},
  {id:"tetris", t:"Tetris", y:2023, ty:"peli", g:"Drama", pf:"Apple TV+", seen:true, wiki:"Tetris (film)"},
  {id:"genius", t:"Genius", y:2017, ty:"serie", g:"Drama", pf:"Disney+", seen:true, wiki:"Genius (American TV series)"},
  {id:"gifted", t:"Un don excepcional", y:2017, ty:"peli", g:"Drama", pf:"Disney+", seen:true, wiki:"Gifted (film)"},
  {id:"silence-of-the-lambs", t:"El silencio de los inocentes", y:1991, ty:"peli", g:"Thriller", pf:"Netflix", seen:true, wiki:"The Silence of the Lambs (film)"},
  {id:"unbearable-weight", t:"El peso del talento", y:2022, ty:"peli", g:"Comedia", pf:"Netflix", seen:true, wiki:"The Unbearable Weight of Massive Talent"},
  {id:"death-at-a-funeral", t:"Muerte en un funeral", y:2007, ty:"peli", g:"Comedia", pf:"Netflix", seen:true, wiki:"Death at a Funeral (2007 film)"},
  {id:"reacher", t:"Reacher", y:2022, ty:"serie", g:"Acción", pf:"Prime Video", now:true, wiki:"Reacher (TV series)",
   v:"T1 y T2 vistas, retomando por la T4, que adapta Gone Tomorrow y salió con 100% en RT. Cada temporada es una novela distinta: la T3 se puede saltear."},
  {id:"lord-of-war", t:"El señor de la guerra", y:2005, ty:"peli", g:"Crimen", pf:"Netflix", seen:true, wiki:"Lord of War"},
  {id:"equalizer-1", t:"El justiciero", y:2014, ty:"peli", g:"Acción", pf:"Netflix", seen:true, wiki:"The Equalizer (film)"},
  {id:"equalizer-2", t:"El justiciero 2", y:2018, ty:"peli", g:"Acción", pf:"Netflix", seen:true, wiki:"The Equalizer 2"},
  {id:"the-kingdom", t:"The Kingdom", y:2007, ty:"peli", g:"Acción", pf:"Netflix", seen:true, wiki:"The Kingdom (2007 film)"},
  {id:"tron-legacy", t:"Tron: Legacy", y:2010, ty:"peli", g:"Sci-fi", pf:"Disney+", seen:true, wiki:"Tron: Legacy"},
  {id:"moon-knight", t:"Moon Knight", y:2022, ty:"serie", g:"Acción", pf:"Disney+", seen:true, wiki:"Moon Knight (miniseries)"},
  {id:"big-hero-6", t:"Grandes héroes", y:2014, ty:"peli", g:"Animación", pf:"Disney+", seen:true, wiki:"Big Hero 6 (film)"},
  {id:"creed", t:"Creed", y:2015, ty:"peli", g:"Drama", pf:"Netflix", seen:true, wiki:"Creed (film)"},
  {id:"creed-2", t:"Creed II", y:2018, ty:"peli", g:"Drama", pf:"Netflix", seen:true, wiki:"Creed II"},
  {id:"creed-3", t:"Creed III", y:2023, ty:"peli", g:"Drama", pf:"Prime Video", seen:true, wiki:"Creed III"},
  {id:"lion-king", t:"El rey león", y:1994, ty:"peli", g:"Animación", pf:"Disney+", seen:true, wiki:"The Lion King"},
  {id:"power-of-the-dog", t:"El poder del perro", y:2021, ty:"peli", g:"Western", pf:"Netflix", seen:true, wiki:"The Power of the Dog (film)"},
  {id:"sully", t:"Sully", y:2016, ty:"peli", g:"Drama", pf:"Netflix", seen:true, wiki:"Sully (film)"},
  {id:"jack-reacher-peli", t:"Jack Reacher", y:2012, ty:"peli", g:"Acción", pf:"Paramount+", seen:true, wiki:"Jack Reacher (film)"},
  {id:"seven-pounds", t:"Siete almas", y:2008, ty:"peli", g:"Drama", pf:"Netflix", seen:true, wiki:"Seven Pounds"},
  {id:"tropic-thunder", t:"Tropic Thunder", y:2008, ty:"peli", g:"Comedia", pf:"Netflix", seen:true, wiki:"Tropic Thunder"},
  {id:"nobody", t:"Nadie", y:2021, ty:"peli", g:"Acción", pf:"Netflix", seen:true, wiki:"Nobody (2021 film)"},
  {id:"enemy-of-the-state", t:"Enemigo público", y:1998, ty:"peli", g:"Thriller", pf:"Disney+", seen:true, wiki:"Enemy of the State (film)"},
  {id:"black-hawk-down", t:"La caída del halcón negro", y:2001, ty:"peli", g:"Bélico", pf:"Netflix", seen:true, wiki:"Black Hawk Down (film)"},
  {id:"13-hours", t:"13 horas: los soldados secretos de Bengasi", y:2016, ty:"peli", g:"Bélico", pf:"Paramount+", seen:true, wiki:"13 Hours: The Secret Soldiers of Benghazi"},
  {id:"annihilation", t:"Aniquilación", y:2018, ty:"peli", g:"Sci-fi", pf:"Netflix", seen:true, wiki:"Annihilation (film)"},
  {id:"iron-giant", t:"El gigante de hierro", y:1999, ty:"peli", g:"Animación", pf:"Max", seen:true, wiki:"The Iron Giant"},
  {id:"the-fighter", t:"The Fighter", y:2010, ty:"peli", g:"Drama", pf:"Netflix", seen:true, wiki:"The Fighter"},
  {id:"blade-runner-2049", t:"Blade Runner 2049", y:2017, ty:"peli", g:"Sci-fi", pf:"Max", seen:true, wiki:"Blade Runner 2049"},
  {id:"green-book", t:"Green Book", y:2018, ty:"peli", g:"Drama", pf:"Netflix", seen:true, wiki:"Green Book (film)"},
  {id:"eeaao", t:"Todo en todas partes al mismo tiempo", y:2022, ty:"peli", g:"Sci-fi", pf:"Prime Video", seen:true, wiki:"Everything Everywhere All at Once"},
  {id:"bullet-train", t:"Bullet Train", y:2022, ty:"peli", g:"Acción", pf:"Netflix", seen:true, wiki:"Bullet Train (film)"},
  {id:"race", t:"Race", y:2016, ty:"peli", g:"Deporte", pf:"Netflix", seen:true, wiki:"Race (2016 film)"},
  {id:"black-adam", t:"Black Adam", y:2022, ty:"peli", g:"Acción", pf:"Max", seen:true, wiki:"Black Adam (film)"},
  {id:"the-menu", t:"El menú", y:2022, ty:"peli", g:"Terror", pf:"Disney+", seen:true, wiki:"The Menu (2022 film)"},
  {id:"enola-holmes", t:"Enola Holmes", y:2020, ty:"peli", g:"Thriller", pf:"Netflix", seen:true, wiki:"Enola Holmes (film)"},
  {id:"the-walking-dead", t:"The Walking Dead", y:2010, ty:"serie", g:"Terror", pf:"Netflix", seen:true, wiki:"The Walking Dead (TV series)"},
  {id:"better-call-saul", t:"Better Call Saul", y:2015, ty:"serie", g:"Crimen", pf:"Netflix", seen:true, wiki:"Better Call Saul"},
  {id:"the-northman", t:"El hombre del norte", y:2022, ty:"peli", g:"Acción", pf:"Prime Video", seen:true, wiki:"The Northman"},
  {id:"predator", t:"Depredador", y:1987, ty:"peli", g:"Acción", pf:"Disney+", seen:true, wiki:"Predator (film)"},
  {id:"prey", t:"Prey", y:2022, ty:"peli", g:"Acción", pf:"Disney+", seen:true, wiki:"Prey (2022 film)"},
  {id:"the-banker", t:"El banquero", y:2020, ty:"peli", g:"Drama", pf:"Apple TV+", seen:true, wiki:"The Banker (2020 film)"},
  {id:"black-phone", t:"El teléfono negro", y:2021, ty:"peli", g:"Terror", pf:"Netflix", seen:true, wiki:"The Black Phone"},
  {id:"contratiempo", t:"Contratiempo", y:2016, ty:"peli", g:"Thriller", pf:"Netflix", seen:true, wiki:"The Invisible Guest"},
  {id:"interstellar", t:"Interstellar", y:2014, ty:"peli", g:"Sci-fi", pf:"Paramount+", seen:true, wiki:"Interstellar (film)"},
  {id:"hannibal", t:"Hannibal", y:2001, ty:"peli", g:"Thriller", pf:"Netflix", seen:true, wiki:"Hannibal (2001 film)"},
  {id:"lotr", t:"El señor de los anillos", y:2001, ty:"peli", g:"Fantasía", pf:"Max", seen:true, wiki:"The Lord of the Rings (film series)"},
  {id:"free-guy", t:"Free Guy", y:2021, ty:"peli", g:"Comedia", pf:"Disney+", seen:true, wiki:"Free Guy"},
  {id:"devil-wears-prada", t:"El diablo viste a la moda", y:2006, ty:"peli", g:"Comedia", pf:"Disney+", seen:true, wiki:"The Devil Wears Prada (film)"},
  {id:"hercules", t:"Hércules", y:1997, ty:"peli", g:"Animación", pf:"Disney+", seen:true, wiki:"Hercules (1997 film)"},
  {id:"pirates-caribbean", t:"Piratas del Caribe", y:2003, ty:"peli", g:"Fantasía", pf:"Disney+", seen:true, wiki:"Pirates of the Caribbean (film series)"},
  {id:"die-hard", t:"Duro de matar", y:1988, ty:"peli", g:"Acción", pf:"Disney+", seen:true, wiki:"Die Hard"},
  {id:"deadpool", t:"Deadpool 1 y 2", y:2016, ty:"peli", g:"Acción", pf:"Disney+", seen:true, wiki:"Deadpool (film)"},
  {id:"the-terminal", t:"La terminal", y:2004, ty:"peli", g:"Comedia", pf:"Netflix", seen:true, wiki:"The Terminal"},
  {id:"parasite", t:"Parásitos", y:2019, ty:"peli", g:"Thriller", pf:"Max", seen:true, wiki:"Parasite (2019 film)"},
  {id:"miss-sloane", t:"Miss Sloane", y:2016, ty:"peli", g:"Drama", pf:"Netflix", seen:true, wiki:"Miss Sloane"},
  {id:"ad-astra", t:"Ad Astra", y:2019, ty:"peli", g:"Sci-fi", pf:"Disney+", seen:true, wiki:"Ad Astra (film)"},
  {id:"gemini-man", t:"Proyecto Géminis", y:2019, ty:"peli", g:"Acción", pf:"Paramount+", seen:true, wiki:"Gemini Man (film)"},
  {id:"it-2", t:"It: Capítulo 2", y:2019, ty:"peli", g:"Terror", pf:"Max", seen:true, wiki:"It Chapter Two"},
  {id:"da-vinci-code", t:"El código Da Vinci", y:2006, ty:"peli", g:"Thriller", pf:"Netflix", seen:true, wiki:"The Da Vinci Code (film)"},
  {id:"inferno", t:"Inferno", y:2016, ty:"peli", g:"Thriller", pf:"Netflix", seen:true, wiki:"Inferno (2016 film)"},
  {id:"a-quiet-place", t:"Un lugar en silencio", y:2018, ty:"peli", g:"Terror", pf:"Paramount+", seen:true, wiki:"A Quiet Place (film)"},
  {id:"love-actually", t:"Realmente amor", y:2003, ty:"peli", g:"Comedia", pf:"Netflix", seen:true, wiki:"Love Actually"},
  {id:"detective-pikachu", t:"Detective Pikachu", y:2019, ty:"peli", g:"Fantasía", pf:"Max", seen:true, wiki:"Pokémon Detective Pikachu"},
  {id:"the-notebook", t:"Diario de una pasión", y:2004, ty:"peli", g:"Drama", pf:"Netflix", seen:true, wiki:"The Notebook (2004 film)"},
  {id:"batman-begins", t:"Batman Begins", y:2005, ty:"peli", g:"Acción", pf:"Max", seen:true, wiki:"Batman Begins"},
  {id:"the-dark-knight", t:"El caballero de la noche", y:2008, ty:"peli", g:"Acción", pf:"Max", seen:true, wiki:"The Dark Knight"},
  {id:"dark-knight-rises", t:"El caballero de la noche asciende", y:2012, ty:"peli", g:"Acción", pf:"Max", seen:true, wiki:"The Dark Knight Rises"},
  {id:"shrek", t:"Shrek", y:2001, ty:"peli", g:"Animación", pf:"Netflix", seen:true, wiki:"Shrek"},
  {id:"what-happened-to-monday", t:"Siete hermanas", y:2017, ty:"peli", g:"Sci-fi", pf:"Netflix", seen:true, wiki:"What Happened to Monday"},

  /* ─────────── De las listas de Netflix ─────────── */
  {id:"all-quiet-2022", t:"Sin novedad en el frente", y:2022, ty:"peli", g:"Bélico", pf:"Netflix", tier:"S", wiki:"All Quiet on the Western Front (2022 film)",
   v:"Brutal y sin épica. La mejor película de guerra de la década."},
  {id:"society-of-the-snow", t:"La sociedad de la nieve", y:2023, ty:"peli", g:"Drama", pf:"Netflix", tier:"S", wiki:"Society of the Snow",
   v:"Bayona haciendo lo que nadie pudo con esta historia. Siendo de la región, es obligatoria."},
  {id:"train-to-busan", t:"Train to Busan", y:2016, ty:"peli", g:"Acción", pf:"Netflix", tier:"S", wiki:"Train to Busan",
   v:"Zombies con motor de película de acción. Cero fuego lento: es justo tu género."},
  {id:"beef", t:"Beef", y:2023, ty:"serie", g:"Comedia", pf:"Netflix", tier:"S", wiki:"Beef (TV series)",
   v:"Empieza con un bocinazo y termina en otro lado. Diez capítulos que no aflojan."},
  {id:"atlanta", t:"Atlanta", y:2016, ty:"serie", g:"Comedia", pf:"Netflix", tier:"S", wiki:"Atlanta (TV series)",
   v:"Rara y brillante. Cada capítulo se anima a ser una cosa distinta."},
  {id:"maid", t:"Maid", y:2021, ty:"serie", g:"Drama", pf:"Netflix", tier:"A", wiki:"Maid (miniseries)",
   v:"Diez capítulos durísimos y perfectos. Margaret Qualley sostiene todo."},
  {id:"yellowstone", t:"Yellowstone", y:2018, ty:"serie", g:"Western", pf:"Netflix", tier:"A", wiki:"Yellowstone (American TV series)",
   v:"Succession con caballos. Costner y un culebrón de tierras que funciona muy bien."},
  {id:"wolfs-call", t:"El canto del lobo", y:2019, ty:"peli", g:"Thriller", pf:"Netflix", tier:"A", wiki:"The Wolf's Call",
   v:"Submarinos franceses y tensión de sonar, sin grasa. Muy tu palo."},
  {id:"wake-up-dead-man", t:"Wake Up Dead Man", y:2025, ty:"peli", g:"Thriller", pf:"Netflix", tier:"A", wiki:"Wake Up Dead Man: A Knives Out Mystery",
   v:"La mejor Knives Out desde la primera. Más oscura, con Josh O'Connor a la par de Craig."},
  {id:"frankenstein-2025", t:"Frankenstein", y:2025, ty:"peli", g:"Drama", pf:"Netflix", tier:"A", wiki:"Frankenstein (2025 film)",
   v:"Del Toro en estado puro. Melancólica, no de sustos: no te va a pasar lo del terror lento."},
  {id:"nisman", t:"Nisman", y:2019, ty:"serie", g:"True Crime", pf:"Netflix", tier:"A", wiki:"Nisman: The Prosecutor, the President and the Spy",
   v:"La reconstrucción más completa del caso. Seis capítulos, ninguno de relleno."},
  {id:"dont-fk-with-cats", t:"Don't F**k with Cats", y:2019, ty:"serie", g:"True Crime", pf:"Netflix", tier:"A", wiki:"Don't F**k with Cats: Hunting an Internet Killer",
   v:"Tres capítulos, se ven de una sentada. El mejor true crime del catálogo."},
  {id:"life-on-our-planet", t:"Life on Our Planet", y:2023, ty:"serie", g:"Naturaleza", pf:"Netflix", tier:"A", wiki:"Life on Our Planet",
   v:"Attenborough con el equipo de Spielberg. La reconstrucción prehistórica es impresionante."},
  {id:"pangolin", t:"Pangolin: Kulu's Journey", y:2025, ty:"peli", g:"Naturaleza", pf:"Netflix", tier:"A", wiki:"Pangolin: Kulu's Journey",
   v:"De la directora de Mi maestro el pulpo. Noventa minutos hermosos y tristes."},
  {id:"if-anything-happens", t:"If Anything Happens I Love You", y:2020, ty:"peli", g:"Animación", pf:"Netflix", tier:"A", wiki:"If Anything Happens I Love You",
   v:"Doce minutos. Te va a partir al medio. Ganó el Oscar a corto animado."},
  {id:"carry-on", t:"Carry-On", y:2024, ty:"peli", g:"Acción", pf:"Netflix", tier:"B", wiki:"Carry-On (film)",
   v:"Thriller de aeropuerto eficiente y descartable. Irónicamente, ideal para el avión."},
  {id:"the-gentlemen", t:"The Gentlemen", y:2024, ty:"serie", g:"Comedia", pf:"Netflix", tier:"B", wiki:"The Gentlemen (TV series)",
   v:"Guy Ritchie en piloto automático, que igual divierte. Capítulos livianos."},
  {id:"devil-all-the-time", t:"El diablo a todas horas", y:2020, ty:"peli", g:"Thriller", pf:"Netflix", tier:"B", wiki:"The Devil All the Time (film)",
   v:"Elenco tremendo, tono uniformemente sombrío. Larga y sin respiro."},
  {id:"the-spy", t:"The Spy", y:2019, ty:"serie", g:"Thriller", pf:"Netflix", tier:"B", wiki:"The Spy (miniseries)",
   v:"Sacha Baron Cohen serio y creíble. Seis capítulos sobre la historia real de Eli Cohen."},
  {id:"the-whale", t:"The Whale", y:2022, ty:"peli", g:"Drama", pf:"Netflix", tier:"B", wiki:"The Whale (2022 film)",
   v:"Fraser se ganó el Oscar. Es teatro filmado en un cuarto: te va a pesar el ritmo."},
  {id:"the-two-popes", t:"Los dos papas", y:2019, ty:"peli", g:"Drama", pf:"Netflix", tier:"B", wiki:"The Two Popes",
   v:"Dos actores enormes charlando dos horas. Más liviana y graciosa de lo que promete."},
  {id:"rafa", t:"Rafa", y:2026, ty:"serie", g:"Deporte", pf:"Netflix", tier:"B", wiki:"Rafa (miniseries)", search:"Rafa Netflix Nadal docuseries",
   v:"Acceso brutal al archivo personal, pero mantiene distancia emocional. Cuatro capítulos."},
  {id:"arnold", t:"Arnold", y:2023, ty:"serie", g:"Deporte", pf:"Netflix", tier:"B", wiki:"Arnold (miniseries)",
   v:"Tres capítulos: fisicoculturismo, Hollywood, política. El primero es el mejor de lejos."},
  {id:"big-vape", t:"Big Vape", y:2023, ty:"serie", g:"Documental", pf:"Netflix", tier:"B", wiki:"Big Vape: The Rise and Fall of Juul",
   v:"Auge y caída de Juul. Ordenada y bien contada, sin nada que la distinga."},
  {id:"our-universe", t:"Our Universe", y:2022, ty:"serie", g:"Naturaleza", pf:"Netflix", tier:"B", wiki:"Our Universe (TV series)",
   v:"Cosmos y naturaleza mezclados, con Morgan Freeman. Preciosa y liviana."},
  {id:"wednesday", t:"Merlina", y:2022, ty:"serie", g:"Comedia", pf:"Netflix", tier:"C", wiki:"Wednesday (TV series)",
   v:"Ortega sola contra una serie floja. La T2 empeoró el promedio."},
  {id:"startup", t:"StartUp", y:2016, ty:"serie", g:"Crimen", pf:"Netflix", tier:"C", wiki:"StartUp (TV series)",
   v:"Entretenida y absolutamente olvidable. Tres temporadas es mucho pedir."},
  {id:"into-the-night", t:"Into the Night", y:2020, ty:"serie", g:"Sci-fi", pf:"Netflix", tier:"C", wiki:"Into the Night (TV series)",
   v:"Premisa buenísima, ejecución de saldo. Salva que son capítulos de treinta minutos."},
  {id:"machos-alfa", t:"Machos Alfa", y:2022, ty:"serie", g:"Comedia", pf:"Netflix", tier:"C", wiki:"Alpha Males (TV series)",
   v:"Comedia española de trazo grueso. Sirve de fondo, poco más."},
  {id:"epstein-filthy-rich", t:"Jeffrey Epstein: Filthy Rich", y:2020, ty:"serie", g:"True Crime", pf:"Netflix", tier:"C", wiki:"Jeffrey Epstein: Filthy Rich",
   v:"Sensacionalista y desprolija. El caso da para muchísimo más."},
  {id:"trainwreck-astroworld", t:"Trainwreck: Astroworld", y:2025, ty:"peli", g:"True Crime", pf:"Netflix", tier:"C", wiki:"Trainwreck: The Astroworld Tragedy",
   v:"Cuarenta y cinco minutos de recortes de noticias. No aporta nada nuevo."},
  {id:"money-explained", t:"Money, Explained", y:2021, ty:"serie", g:"Documental", pf:"Netflix", tier:"C", wiki:"Explained (TV series)",
   v:"Formato Vox. Superficial si ya sabés algo de los temas que toca."},

  /* ─────────── Star Wars, Alien y compañía ─────────── */
  {id:"empire-strikes-back", t:"El imperio contraataca", y:1980, ty:"peli", g:"Sci-fi", pf:"Disney+", tier:"S", wiki:"The Empire Strikes Back",
   v:"El pico de todo Star Wars. Más oscura, mejor escrita, mejor final."},
  {id:"a-new-hope", t:"Una nueva esperanza", y:1977, ty:"peli", g:"Sci-fi", pf:"Disney+", tier:"S", wiki:"Star Wars (film)",
   v:"Tu punto de entrada. Autoconclusiva y sin deberes previos."},
  {id:"andor", t:"Andor", y:2022, ty:"serie", g:"Sci-fi", pf:"Disney+", tier:"S", wiki:"Andor (TV series)",
   v:"El mejor Star Wars escrito, de lejos. Adulto, político, casi sin sables láser."},
  {id:"aliens", t:"Aliens", y:1986, ty:"peli", g:"Acción", pf:"Disney+", tier:"S", wiki:"Aliens (film)",
   v:"Tu película. Cameron agarra el terror del 79 y lo convierte en guerra. Mirá el Director's Cut."},
  {id:"12-monkeys", t:"12 monos", y:1995, ty:"peli", g:"Sci-fi", pf:"Alquiler", tier:"S", wiki:"12 Monkeys",
   v:"Gilliam, Willis y un Brad Pitt irreconocible. Viaje en el tiempo bien hecho."},
  {id:"return-of-the-jedi", t:"El retorno del Jedi", y:1983, ty:"peli", g:"Sci-fi", pf:"Disney+", tier:"A", wiki:"Return of the Jedi",
   v:"Cierra el arco como corresponde. Perdonale los ewoks."},
  {id:"rogue-one", t:"Rogue One", y:2016, ty:"peli", g:"Sci-fi", pf:"Disney+", tier:"A", wiki:"Rogue One",
   v:"La mejor película de Star Wars moderna. Se ve justo antes del Episodio IV."},
  {id:"the-mandalorian", t:"The Mandalorian", y:2019, ty:"serie", g:"Sci-fi", pf:"Disney+", tier:"A", wiki:"The Mandalorian",
   v:"Western espacial con el espíritu de la trilogía original. T1 y T2; después baja."},
  {id:"alien-romulus", t:"Alien: Romulus", y:2024, ty:"peli", g:"Acción", pf:"Disney+", tier:"A", wiki:"Alien: Romulus",
   v:"Lo mejor de la saga desde 1986. Más nerviosa que contemplativa, te va a ir bien."},
  {id:"dune-prophecy", t:"Dune: Prophecy", y:2024, ty:"serie", g:"Sci-fi", pf:"Max", tier:"B", wiki:"Dune: Prophecy",
   v:"Siendo fan de Dune, obligatoria de probar. Es política Bene Gesserit, no la epopeya de Paul."},
  {id:"devil-wears-prada-2", t:"El diablo viste a la moda 2", y:2026, ty:"peli", g:"Comedia", pf:"Cine", tier:"B", wiki:"The Devil Wears Prada 2",
   v:"79% en RT, mejor recibida que la original. Comfort watch de manual."},
  {id:"avatar-aang-2026", t:"Avatar Aang: The Last Airbender", y:2026, ty:"peli", g:"Animación", pf:"Paramount+", tier:"B", wiki:"The Legend of Aang: The Last Airbender",
   v:"Preciosa, pero es una temporada comprimida en 99 minutos. Ya viste la serie, así que te va a rendir."},
  {id:"alien-3", t:"Alien 3", y:1992, ty:"peli", g:"Terror", pf:"Disney+", tier:"C", wiki:"Alien 3",
   v:"Debut de Fincher, que la repudió. Oscura y frustrante. Saltala en la primera pasada."},
  {id:"prometheus", t:"Prometheus", y:2012, ty:"peli", g:"Sci-fi", pf:"Disney+", tier:"C", wiki:"Prometheus (2012 film)",
   v:"Ideas grandes, ejecución floja y personajes que toman decisiones absurdas."},
  {id:"alien-covenant", t:"Alien: Covenant", y:2017, ty:"peli", g:"Terror", pf:"Disney+", tier:"C", wiki:"Alien: Covenant",
   v:"Mejor que Prometheus, igual dispareja. Sólo si querés la línea completa."},
  {id:"mercy", t:"Mercy", y:2026, ty:"peli", g:"Sci-fi", pf:"Prime Video", tier:"D", wiki:"Mercy (2026 film)",
   v:"25% en RT. Pratt atado a una silla noventa minutos. El público la banca, la crítica la fusiló."},
  {id:"phantom-menace", t:"La amenaza fantasma", y:1999, ty:"peli", g:"Sci-fi", pf:"Disney+", tier:"D", wiki:"The Phantom Menace",
   v:"No es tu entrada a Star Wars ni de casualidad. Dejala para cuando ya seas fan."},
  {id:"alien-resurrection", t:"Alien: Resurrección", y:1997, ty:"peli", g:"Terror", pf:"Disney+", tier:"D", wiki:"Alien Resurrection",
   v:"Sólo si sos completista obsesivo. No lo sos todavía."},
  {id:"alien-1979", t:"Alien", y:1979, ty:"peli", g:"Terror", pf:"Disney+", seen:true, wiki:"Alien (film)"},

  /* ─────────── MCU: las 32 en orden de estreno, todas vistas ─────────── */
  {id:"mcu-01", t:"Iron Man", y:2008, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:1, wiki:"Iron Man (2008 film)"},
  {id:"mcu-02", t:"El increíble Hulk", y:2008, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:2, wiki:"The Incredible Hulk (film)"},
  {id:"mcu-03", t:"Iron Man 2", y:2010, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:3, wiki:"Iron Man 2"},
  {id:"mcu-04", t:"Thor", y:2011, ty:"peli", g:"Fantasía", pf:"Disney+", seen:true, saga:"MCU", n:4, wiki:"Thor (film)"},
  {id:"mcu-05", t:"Capitán América: El primer vengador", y:2011, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:5, wiki:"Captain America: The First Avenger"},
  {id:"mcu-06", t:"Los Vengadores", y:2012, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:6, wiki:"The Avengers (2012 film)"},
  {id:"mcu-07", t:"Iron Man 3", y:2013, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:7, wiki:"Iron Man 3"},
  {id:"mcu-08", t:"Thor: El mundo oscuro", y:2013, ty:"peli", g:"Fantasía", pf:"Disney+", seen:true, saga:"MCU", n:8, wiki:"Thor: The Dark World"},
  {id:"mcu-09", t:"Guardianes de la Galaxia", y:2014, ty:"peli", g:"Sci-fi", pf:"Disney+", seen:true, saga:"MCU", n:9, wiki:"Guardians of the Galaxy (film)"},
  {id:"mcu-10", t:"Capitán América: El soldado de invierno", y:2014, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:10, wiki:"Captain America: The Winter Soldier"},
  {id:"mcu-11", t:"Vengadores: La era de Ultrón", y:2015, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:11, wiki:"Avengers: Age of Ultron"},
  {id:"mcu-12", t:"Ant-Man", y:2015, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:12, wiki:"Ant-Man (film)"},
  {id:"mcu-13", t:"Capitán América: Civil War", y:2016, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:13, wiki:"Captain America: Civil War"},
  {id:"mcu-14", t:"Doctor Strange", y:2016, ty:"peli", g:"Fantasía", pf:"Disney+", seen:true, saga:"MCU", n:14, wiki:"Doctor Strange (2016 film)"},
  {id:"mcu-15", t:"Guardianes de la Galaxia Vol. 2", y:2017, ty:"peli", g:"Sci-fi", pf:"Disney+", seen:true, saga:"MCU", n:15, wiki:"Guardians of the Galaxy Vol. 2"},
  {id:"mcu-16", t:"Spider-Man: De regreso a casa", y:2017, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:16, wiki:"Spider-Man: Homecoming"},
  {id:"mcu-17", t:"Thor: Ragnarok", y:2017, ty:"peli", g:"Comedia", pf:"Disney+", seen:true, saga:"MCU", n:17, wiki:"Thor: Ragnarok"},
  {id:"mcu-18", t:"Pantera Negra", y:2018, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:18, wiki:"Black Panther (film)"},
  {id:"mcu-19", t:"Vengadores: Infinity War", y:2018, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:19, wiki:"Avengers: Infinity War"},
  {id:"mcu-20", t:"Ant-Man y la Avispa", y:2018, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:20, wiki:"Ant-Man and the Wasp"},
  {id:"mcu-21", t:"Capitana Marvel", y:2019, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:21, wiki:"Captain Marvel (film)"},
  {id:"mcu-22", t:"Vengadores: Endgame", y:2019, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:22, wiki:"Avengers: Endgame"},
  {id:"mcu-23", t:"Spider-Man: Lejos de casa", y:2019, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:23, wiki:"Spider-Man: Far From Home"},
  {id:"mcu-24", t:"Viuda Negra", y:2021, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:24, wiki:"Black Widow (2021 film)"},
  {id:"mcu-25", t:"Shang-Chi y la leyenda de los Diez Anillos", y:2021, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:25, wiki:"Shang-Chi and the Legend of the Ten Rings"},
  {id:"mcu-26", t:"Eternals", y:2021, ty:"peli", g:"Sci-fi", pf:"Disney+", seen:true, saga:"MCU", n:26, wiki:"Eternals (film)"},
  {id:"mcu-27", t:"Spider-Man: Sin camino a casa", y:2021, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:27, wiki:"Spider-Man: No Way Home"},
  {id:"mcu-28", t:"Doctor Strange en el multiverso de la locura", y:2022, ty:"peli", g:"Fantasía", pf:"Disney+", seen:true, saga:"MCU", n:28, wiki:"Doctor Strange in the Multiverse of Madness"},
  {id:"mcu-29", t:"Thor: Amor y trueno", y:2022, ty:"peli", g:"Comedia", pf:"Disney+", seen:true, saga:"MCU", n:29, wiki:"Thor: Love and Thunder"},
  {id:"mcu-30", t:"Pantera Negra: Wakanda por siempre", y:2022, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"MCU", n:30, wiki:"Black Panther: Wakanda Forever"},
  {id:"mcu-31", t:"Ant-Man y la Avispa: Quantumanía", y:2023, ty:"peli", g:"Sci-fi", pf:"Disney+", seen:true, saga:"MCU", n:31, wiki:"Ant-Man and the Wasp: Quantumania"},
  {id:"mcu-32", t:"Guardianes de la Galaxia Vol. 3", y:2023, ty:"peli", g:"Sci-fi", pf:"Disney+", seen:true, saga:"MCU", n:32, wiki:"Guardians of the Galaxy Vol. 3"},

  /* ─────────── X-Men: todas vistas, con tu ranking ─────────── */
  {id:"xm-logan", t:"Logan", y:2017, ty:"peli", g:"Drama", pf:"Disney+", seen:true, saga:"X-Men", rank:1, orden:10, wiki:"Logan (film)"},
  {id:"xm-first-class", t:"X-Men: Primera generación", y:2011, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"X-Men", rank:2, orden:1, wiki:"X-Men: First Class"},
  {id:"xm-dofp", t:"X-Men: Días del futuro pasado", y:2014, ty:"peli", g:"Sci-fi", pf:"Disney+", seen:true, saga:"X-Men", rank:3, orden:7, wiki:"X-Men: Days of Future Past"},
  {id:"xm-x2", t:"X2", y:2003, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"X-Men", rank:4, orden:4, wiki:"X2 (film)"},
  {id:"xm-xmen", t:"X-Men", y:2000, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"X-Men", rank:5, orden:3, wiki:"X-Men (film)"},
  {id:"xm-the-wolverine", t:"Wolverine inmortal", y:2013, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"X-Men", rank:6, orden:6, wiki:"The Wolverine (film)"},
  {id:"xm-apocalypse", t:"X-Men: Apocalipsis", y:2016, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"X-Men", rank:7, orden:8, wiki:"X-Men: Apocalypse"},
  {id:"xm-last-stand", t:"X-Men: La batalla final", y:2006, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"X-Men", rank:8, orden:5, wiki:"X-Men: The Last Stand"},
  {id:"xm-origins", t:"X-Men orígenes: Wolverine", y:2009, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"X-Men", rank:9, orden:2, wiki:"X-Men Origins: Wolverine"},
  {id:"xm-dark-phoenix", t:"X-Men: Fénix Oscura", y:2019, ty:"peli", g:"Acción", pf:"Disney+", seen:true, saga:"X-Men", rank:10, orden:9, wiki:"Dark Phoenix (film)"},
];
